resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=b41b0774cc145b4a39d0ca07a3c4648ba2e63221
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: b41b0774cc145b4a39d0ca07a3c4648ba2e63221

configMapGenerator:
- literals:
  - GITHUB_ORG="ralphbean-appstudio"
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
